---

- hosts: all
  become: true
  tasks:
  - name: Install remove Apache2 and php package
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      update_cache: yes 
      state: absent
    when : ansible_distribution | lower in ["ubuntu", "debian"]

  - name: Install Apache2 package in centos
    dnf:
      name: 
      - httpd
      - php
      state: absent
      update_cache: yes
    when : ansible_distribution | lower in ["centos"]


 