---

- hosts: all
  become: true
  tasks:

  - name: Installremove Apache2 package
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: absent
      update_cache: yes
    when : ansible_distribution in ["Ubuntu", "Debian"]
  - name: Install Apache2 and php packages in centos
    dnf:
      name: 
        - httpd
        - php
      state: absent
      update_cache: yes
    when : ansible_distribution in ["CentOS"]

 