---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (CentoS)
    tags: always
    dnf:
      update_only: yes
      update_cache: yes
    when : ansible_distribution | lower in ["centos", "redhat", "fedora"]

  - name: install updates (Ubuntu/Debian)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when : ansible_distribution | lower in ["ubuntu", "debian"]

- hosts: web_servers
  become: true
  tasks:

  - name: Install Apache2 and php package
    tags: apache,apache2,ubuntu
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
    when : ansible_distribution  == "Ubuntu"



  - name: Install Apache2 and php package in centos
    tags: apache,httpd,centos
    dnf:
      name: 
      - httpd
      - php
      state: latest
    when : ansible_distribution | lower in ["centos"]

  - name: copy default html file for a site
    tags: apache,apache2,ubuntu
    copy:
      src: files/default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644


    
- hosts: db_servers
  become: true
  tasks:

  - name: Install Maria db server package
    tags: mariadb,db,ubuntu
    apt:
      name: 
        - mariadb-server
      state: latest
    when : ansible_distribution  in ["Ubuntu", "Debian"]
  
  - name: Install Maria db server package
    tags: mariadb,db,centos
    dnf:
      name: 
        - mariadb
      state: latest
    when : ansible_distribution  in ["CentOS" ]

- hosts: file_servers
  tags: samba
  become: true
  tasks:
  - name: Install Samba server package
    package:
      name: 
        - samba
      state: latest
