- name: Install Apache and php package
  tags: apache, httpd, php
  package:
    name: 
      - "{{ apache_package_name }}"
      - "{{ php_package_name }}"
    state: latest

- name: start and enable apache service 
  tags: apache,httpd
  service:
    name: "{{ apache_service }}"
    state: started
    enabled: yes


- name: Allow HTTPS service (port 443) in the firewall
  ansible.posix.firewalld:
    service: https
    permanent: true
    state: enabled
    immediate: true
  when : ansible_distribution | lower in ["centos"]

- name: Change e-mail address for admin in centos
  tags: apache,apache2,ubuntu
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^ServerAdmin'
    line: ServerAdmin bernardoapelt@outlook.com
  when : ansible_distribution | lower in ["centos"]
  notify: restart_apache


- name: copy default html file for a site
  tags: apache,apache2,ubuntu
  copy:
    src: files/default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644

# this is not needed as the default file is replaced by the copy module below
# - name: delete default html file for a site in centos
#   tags: apache,httpd,centos
#   file: 
#     path: /var/www/html/index.html
#     state: absent